"""Clearly marked sample records, plus the user's eight real business workspaces."""
from datetime import timedelta

def build_seed(day):
    def date(offset=0): return (day+timedelta(days=offset)).isoformat()
    businesses=[
      ('artbit','Artbit Studio','Agency','Primary revenue engine','#7685ff','Facebook, Instagram, LinkedIn','Businesses that need creative marketing','Branding, Campaigns, Client results','Protect daily strategy time'),
      ('vidzones','Vidzones','Video agency','Revenue growth','#00b6a5','Instagram, LinkedIn, YouTube Shorts','Agencies, brands, startups','AI video, Case studies, Before/after','4 social posts per week'),
      ('qfs','QFS','Sourcing business','Revenue growth','#e5a835','LinkedIn, Email, Website','Garment buyers and importers','Sourcing insights, Quality control, Bangladesh manufacturing','Build a qualified B2B pipeline'),
      ('jubayer','I am Jubayer','Personal brand','Long-term brand asset','#7685ff','YouTube, Facebook, LinkedIn, YouTube Shorts','People interested in science, business, AI and creativity','Science, Business, AI, Marketing, Personal journey','2 long-form videos per month'),
      ('cnmotos','CNMOTOS','Media','Automated media asset','#ed7656','Facebook, X, Instagram, Website','Motorsport and automotive readers','News, Analysis, Explainers','Repurpose articles into 5 weekly social posts'),
      ('alabama','AlabamaFootball','Media','Automated media asset','#ce5373','Facebook, X, Instagram, Website','Alabama football followers','News, Analysis, Match coverage','Repurpose articles into 5 weekly social posts'),
      ('biggan','Biggan PiC','Science & commerce','Milestone growth','#3994dc','YouTube, Facebook, Instagram','Science enthusiasts','Science facts, Experiments, Merchandise','Alternate Thursday attention'),
      ('ghuraghuri','GhuraghuriBD','Travel','Milestone growth','#55a97b','Facebook, Instagram, TikTok','Travel enthusiasts in Bangladesh','Destinations, Experiences, Travel tips','Alternate Thursday attention'),
    ]
    result={'businesses':[dict(zip(('id','name','kind','focus','color','channels','target','pillars','goal'),b)) for b in businesses]}
    result['clients']=[{'id':'nahar','name':"Nahar’s Dental Care",'business_id':'artbit','contact':'Doctor / clinic team','email':'','fee':2000000,'status':'Active','notes':'Sample billing amount. Replace with the actual client agreement. Educational Bangla content; blue and white dental style.','demo':True}, {'id':'sample-client','name':'Example Brand','business_id':'artbit','contact':'Client team','fee':3500000,'status':'Onboarding','notes':'Example agency client.','demo':True}]
    result['projects']=[{'id':'p1','title':'October dental content batch','business_id':'artbit','client_id':'nahar','due':date(3),'status':'Review','notes':'Review clinic-approved topics and visual drafts.','demo':True},{'id':'p2','title':'AI product film case study','business_id':'vidzones','due':date(5),'status':'In progress','notes':'Turn the master project into a showcase, carousel and LinkedIn case study.','demo':True},{'id':'p3','title':'Personal brand launch','business_id':'jubayer','due':date(14),'status':'Planned','demo':True}]
    contents=[
      ('c1','Gum health: what bleeding tells you','artbit','nahar','Facebook','Post','In review',2,'Headline and medical claims await doctor review.\nVisual direction: clean blue and white, clear Bengali headline.'),
      ('c2','AI product video: behind the scenes','vidzones','','Instagram','Reel','In review',3,'Show the brief, the creative direction and the final result. Include a short explanation of the production process.'),
      ('c3','A practical garment quality checklist','qfs','','LinkedIn','Carousel','In review',4,'A five-point quality checklist for buyers. Validate each point against your own operating procedures.'),
      ('c4','From one article to five social posts','cnmotos','','Facebook','Post','Approved',3,'Sample repurposing draft. Add a verified source article before publishing.'),
      ('c5','Weekly coverage plan','alabama','','X','Post','Draft',4,'Add a verified article and confirm team news before submitting for review.'),
      ('c6','How I build an AI-first workday','jubayer','','YouTube','Script','Draft',7,'Hook: What if most of your day was spent making decisions instead of repeating tasks?\nAdd your own experience and examples.'),
      ('c7','Science you can wear','biggan','','Instagram','Carousel','Idea',9,'Explore a science-inspired merchandise story.'),
      ('c8','A weekend travel checklist','ghuraghuri','','Facebook','Post','Draft',8,'Add destination-specific advice and verify travel details.'),
      ('c9','October agency content plan','artbit','','LinkedIn','Post','Approved',2,'Show the creative process behind a recent client project. Obtain permission before including client details.'),
    ]
    result['content']=[dict(id=i,title=t,business_id=b,client_id=cl,channel=ch,format=f,status=s,date=date(d),copy=cp,notes='',demo=True) for i,t,b,cl,ch,f,s,d,cp in contents]
    result['leads']=[{'id':'l1','name':'Example Apparel Buyer','business_id':'qfs','contact':'Buying team','value':18000000,'stage':'Qualified','next_date':date(1),'notes':'Sample prospect. Research and verify a real company before outreach.','demo':True},{'id':'l2','name':'Example DTC Brand','business_id':'vidzones','value':8500000,'stage':'Proposal','next_date':date(2),'notes':'Sample opportunity.','demo':True},{'id':'l3','name':'Example Local Business','business_id':'artbit','value':5000000,'stage':'Meeting','next_date':date(),'demo':True}]
    result['invoices']=[{'id':'i1','title':'Nahar’s Dental · monthly retainer','business_id':'artbit','client_id':'nahar','amount':2000000,'paid':0,'date':date(-7),'due':date(-1),'notes':'Sample invoice, not an actual receivable.','demo':True},{'id':'i2','title':'Product film · deposit','business_id':'vidzones','amount':8500000,'paid':8500000,'date':date(-3),'due':date(2),'notes':'Sample paid invoice.','demo':True}]
    result['transactions']=[{'id':'t1','title':'Product film deposit','business_id':'vidzones','kind':'Income','amount':8500000,'date':date(),'category':'Client payment','invoice_id':'i2','demo':True},{'id':'t2','title':'Agency project payment','business_id':'artbit','kind':'Income','amount':6000000,'date':date(),'category':'Project fee','demo':True},{'id':'t3','title':'Freelance editing','business_id':'vidzones','kind':'Expense','amount':1800000,'date':date(),'category':'Production','demo':True},{'id':'t4','title':'Design production','business_id':'artbit','kind':'Expense','amount':1200000,'date':date(),'category':'Production','demo':True},{'id':'t5','title':'Media hosting','business_id':'cnmotos','kind':'Expense','amount':250000,'date':date(),'category':'Hosting','demo':True}]
    result['resources']=[{'id':'r1','name':'AI creative subscription','type':'Subscription','cost':250000,'cycle':'Monthly','renewal':date(6),'owner':'Jubayer','notes':'Sample cost in BDT. Replace with your actual subscription.','demo':True},{'id':'r2','name':'iamjubayer.com','business_id':'jubayer','type':'Domain','cost':180000,'cycle':'Annual','renewal':date(50),'url':'https://iamjubayer.com','owner':'Jubayer','notes':'Sample renewal and cost.','demo':True},{'id':'r3','name':'Brand identity & creative assets','business_id':'artbit','type':'Asset','cost':0,'cycle':'None','notes':'Add the location of your logo, fonts and brand guide.','demo':True},{'id':'r4','name':'Freelance video editor','business_id':'vidzones','type':'Team','cost':0,'cycle':'None','owner':'External collaborator','notes':'Sample resource. Add availability and responsibilities.','demo':True}]
    result['plans']=[{'id':'m1','title':'Vidzones · October visibility','business_id':'vidzones','objective':'Generate qualified video-production inquiries','audience':'Agencies, e-commerce brands, startups','channels':'Instagram, LinkedIn, YouTube Shorts','pillars':'AI video, Case studies, Before/after, Production education','cadence':'4 posts/week: 2 showcases, 1 education, 1 case study','kpi':'Qualified inquiries and booked calls','date':date(),'notes':'Batch repurpose completed projects. Review on Sunday and Thursday.','demo':True}]
    result['recipes']=[{'id':'a1','title':'Article → social pack','trigger':'A new verified website article is ready','steps':'1. Read the source article\n2. Draft platform-specific copy\n3. Prepare an image brief\n4. Submit for review\n5. Publish only after approval','output':'Facebook post, X post, Instagram caption, carousel copy','enabled':False,'demo':True},{'id':'a2','title':'Video → content pack','business_id':'jubayer','trigger':'A long-form video is complete','steps':'1. Identify 3–5 short clips\n2. Draft captions and titles\n3. Draft a website article\n4. Review each asset\n5. Send approved items to the publisher','output':'Shorts, article, social posts, thumbnail concepts','enabled':False,'demo':True},{'id':'a3','title':'QFS lead research','business_id':'qfs','trigger':'A target company is added','steps':'1. Research company fit\n2. Verify buyer/contact\n3. Summarize evidence\n4. Draft personalized outreach\n5. Human review before any message','output':'Qualified lead summary and outreach draft','enabled':False,'demo':True}]
    result['tasks']=[]
    result['reviews']=[]
    return result
